experiment_name: "NCA"
device: "cuda:0"

nca:
  #type: "PENCA"             # Type of the NCA. Options: "NCA", "PENCA", "NoiseNCA"
  type: "NCA"
  graft_initialization: null     # Either null or a path to the pretrained model to use for graft initialization
  #graft_initialization: "results/2DPBR_NCA_SM_sin_nf0_bubbly_0101.jpg"
  output_type: "s"                  # This determines what will be passed to siren

  nca_kwargs:
    channels: 19                   # Number of nca channels
    fc_dim: 128                    # Number of neurons in the hidden layer
#     noise_level: 0.0


siren:
  hidden_features: 32           # Number of neurons in the hidden layer of the SIREN decoder
  hidden_layers: 2              # Number of hidden layers in the SIREN decoder
  outermost_linear: True        # Whether to use a linear layer at the output of the SIREN decoder
  fx: "linear"                  # The preactivation function before the sin. ["linear", "finer", "sinh"]
  activation: "sin"
  num_frequencies: 0          # Number of frequencies in the SIREN decoder
  first_omega_0: 10.0
  hidden_omega_0: 10.0

train:
  epochs: 3000                      # Number of epochs
  batch_size: 2                     # Batch size
  lr: 0.001                         # Learning rate
  lr_decay_steps: [ 1000, 2000 ]    # Learning rate decay steps
  lr_decay_gamma: 0.3               # Learning rate decay factor
  pbr_training: False

  #### NCA related configs ####
  nca_grid_size: [ 100, 100 ]         # Size of the grid for the NCA.
  pool_size: 512                    # Number of samples in the pool. Pool is used to improve long-term stability of MeshNCA
  inject_seed_interval: 32          # Number of steps after which a seed state is injected into the pool
  step_range: [ 32, 64 ]            # Number of update steps during training is sampled randomly from this range

  summary_interval: 250             # Interval for logging the training summary
  
  # Folder containing the texture images (1.jpg to 10.jpg)
  texture_path: "data/cloth_texture/wool_knit/100x100"
  # Folder containing the wear maps (1_colormap.png to 10_colormap.png)
  colormap_path: "data/cloth_texture/colormaps/100x100"

renderer:
  scale_factor: 1                # Scale factor for the renderer. The final resolution will be (nca_grid_size * scale_factor)
  padding: "circular"            # This should ideally be the same as the padding used in the NCA.
  ambient_light: 0.5              # Ambient light intensity
  point_light: 0.7          # Directional light intensity
  fs_shader: "vanilla"          # The fragment shader to use. Either "vanilla" or "simple" or "pbr"


num_channels: { # Number of channels in the model to assign to each target image
  "rgb": 3,

}
loss:
  overflow_loss_weight: 100.0      # Weight of the overflow loss
  appearance_loss_weight: 2.0                    # Weight of the style loss


  #### Appearance loss used for image-guided training. Mostly based on VGG features ####
  appearance_loss_kwargs:
    target_image_size: [ 100, 100 ]            # Resolution for loading the target images
    patch_size: [ 96, 96 ]                # Crops from the generated images will be resized to this size before passing to VGG
    num_scales: 1                             # Number of scales to be used for the style loss
    relative_scale: 1                        # Relative scale of the target image to the generated image. 1.0 = same size, 2.0 = twice the size
    max_image_size: [2048, 2048]            # Images larger than this size will be center cropped (Used to avoid OOM errors when relative scale is large)
    # The single channel images will be expanded to 3 channels for evaluating the VGG-based style loss
    # Sci-fi_Wall_010
    target_images_path: {
       "rgb": "data/colormaps_each_fabrics/wool_knit/jumping/00130_2000x4000_blurred.png",
    }
    # Number of channels in the target images
    include_image_as_feature: False
    num_pseudo_targets: 10
    vgg_layers: [ 1, 6, 11, 18, 25 ]    # VGG layers to be used for the style loss
    #vgg_layers: [18, 25]

result_path: "results_cloth_textures/wool_knit/100x100"
# Uncomment to log training to Weights & Biases
#wandb:
#  project: "Siren+NCA"                # WandB project name
#  key: "YOUR_WANDB_API_KEY"           # WandB key for logging
#  group: "2DNCA - PBR"